services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4343:4242"
    environment:
      - STATIC_DIR=../client
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
    env_file:
      - .env
    restart: unless-stopped

